/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../../common';

export interface RewardRouterV2Interface extends utils.Interface {
  functions: {
    'acceptTransfer(address)': FunctionFragment;
    'batchCompoundForAccounts(address[])': FunctionFragment;
    'batchStakeGmxForAccount(address[],uint256[])': FunctionFragment;
    'bnGmx()': FunctionFragment;
    'bonusGmxTracker()': FunctionFragment;
    'claim()': FunctionFragment;
    'claimEsGmx()': FunctionFragment;
    'claimFees()': FunctionFragment;
    'compound()': FunctionFragment;
    'compoundForAccount(address)': FunctionFragment;
    'esGmx()': FunctionFragment;
    'feeGlpTracker()': FunctionFragment;
    'feeGmxTracker()': FunctionFragment;
    'glp()': FunctionFragment;
    'glpManager()': FunctionFragment;
    'glpVester()': FunctionFragment;
    'gmx()': FunctionFragment;
    'gmxVester()': FunctionFragment;
    'gov()': FunctionFragment;
    'handleRewards(bool,bool,bool,bool,bool,bool,bool)': FunctionFragment;
    'initialize(address,address,address,address,address,address,address,address,address,address,address,address,address)': FunctionFragment;
    'isInitialized()': FunctionFragment;
    'mintAndStakeGlp(address,uint256,uint256,uint256)': FunctionFragment;
    'mintAndStakeGlpETH(uint256,uint256)': FunctionFragment;
    'pendingReceivers(address)': FunctionFragment;
    'setGov(address)': FunctionFragment;
    'signalTransfer(address)': FunctionFragment;
    'stakeEsGmx(uint256)': FunctionFragment;
    'stakeGmx(uint256)': FunctionFragment;
    'stakeGmxForAccount(address,uint256)': FunctionFragment;
    'stakedGlpTracker()': FunctionFragment;
    'stakedGmxTracker()': FunctionFragment;
    'unstakeAndRedeemGlp(address,uint256,uint256,address)': FunctionFragment;
    'unstakeAndRedeemGlpETH(uint256,uint256,address)': FunctionFragment;
    'unstakeEsGmx(uint256)': FunctionFragment;
    'unstakeGmx(uint256)': FunctionFragment;
    'weth()': FunctionFragment;
    'withdrawToken(address,address,uint256)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'acceptTransfer'
      | 'batchCompoundForAccounts'
      | 'batchStakeGmxForAccount'
      | 'bnGmx'
      | 'bonusGmxTracker'
      | 'claim'
      | 'claimEsGmx'
      | 'claimFees'
      | 'compound'
      | 'compoundForAccount'
      | 'esGmx'
      | 'feeGlpTracker'
      | 'feeGmxTracker'
      | 'glp'
      | 'glpManager'
      | 'glpVester'
      | 'gmx'
      | 'gmxVester'
      | 'gov'
      | 'handleRewards'
      | 'initialize'
      | 'isInitialized'
      | 'mintAndStakeGlp'
      | 'mintAndStakeGlpETH'
      | 'pendingReceivers'
      | 'setGov'
      | 'signalTransfer'
      | 'stakeEsGmx'
      | 'stakeGmx'
      | 'stakeGmxForAccount'
      | 'stakedGlpTracker'
      | 'stakedGmxTracker'
      | 'unstakeAndRedeemGlp'
      | 'unstakeAndRedeemGlpETH'
      | 'unstakeEsGmx'
      | 'unstakeGmx'
      | 'weth'
      | 'withdrawToken',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'acceptTransfer',
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: 'batchCompoundForAccounts',
    values: [PromiseOrValue<string>[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'batchStakeGmxForAccount',
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]],
  ): string;
  encodeFunctionData(functionFragment: 'bnGmx', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'bonusGmxTracker',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'claimEsGmx',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'claimFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'compound', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'compoundForAccount',
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: 'esGmx', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'feeGlpTracker',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'feeGmxTracker',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'glp', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'glpManager',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'glpVester', values?: undefined): string;
  encodeFunctionData(functionFragment: 'gmx', values?: undefined): string;
  encodeFunctionData(functionFragment: 'gmxVester', values?: undefined): string;
  encodeFunctionData(functionFragment: 'gov', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'handleRewards',
    values: [
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'isInitialized',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'mintAndStakeGlp',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintAndStakeGlpETH',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'pendingReceivers',
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: 'setGov',
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: 'signalTransfer',
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: 'stakeEsGmx',
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'stakeGmx',
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'stakeGmxForAccount',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'stakedGlpTracker',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'stakedGmxTracker',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'unstakeAndRedeemGlp',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'unstakeAndRedeemGlpETH',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'unstakeEsGmx',
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'unstakeGmx',
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'weth', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'withdrawToken',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
    ],
  ): string;

  decodeFunctionResult(
    functionFragment: 'acceptTransfer',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'batchCompoundForAccounts',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'batchStakeGmxForAccount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'bnGmx', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'bonusGmxTracker',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimEsGmx', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'compound', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'compoundForAccount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'esGmx', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'feeGlpTracker',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'feeGmxTracker',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'glp', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'glpManager', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'glpVester', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'gmx', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'gmxVester', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'gov', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'handleRewards',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isInitialized',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintAndStakeGlp',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintAndStakeGlpETH',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'pendingReceivers',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setGov', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'signalTransfer',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'stakeEsGmx', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'stakeGmx', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'stakeGmxForAccount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'stakedGlpTracker',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'stakedGmxTracker',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'unstakeAndRedeemGlp',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'unstakeAndRedeemGlpETH',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'unstakeEsGmx',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'unstakeGmx', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawToken',
    data: BytesLike,
  ): Result;

  events: {
    'StakeGlp(address,uint256)': EventFragment;
    'StakeGmx(address,address,uint256)': EventFragment;
    'UnstakeGlp(address,uint256)': EventFragment;
    'UnstakeGmx(address,address,uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'StakeGlp'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'StakeGmx'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UnstakeGlp'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UnstakeGmx'): EventFragment;
}

export interface StakeGlpEventObject {
  account: string;
  amount: BigNumber;
}
export type StakeGlpEvent = TypedEvent<
  [string, BigNumber],
  StakeGlpEventObject
>;

export type StakeGlpEventFilter = TypedEventFilter<StakeGlpEvent>;

export interface StakeGmxEventObject {
  account: string;
  token: string;
  amount: BigNumber;
}
export type StakeGmxEvent = TypedEvent<
  [string, string, BigNumber],
  StakeGmxEventObject
>;

export type StakeGmxEventFilter = TypedEventFilter<StakeGmxEvent>;

export interface UnstakeGlpEventObject {
  account: string;
  amount: BigNumber;
}
export type UnstakeGlpEvent = TypedEvent<
  [string, BigNumber],
  UnstakeGlpEventObject
>;

export type UnstakeGlpEventFilter = TypedEventFilter<UnstakeGlpEvent>;

export interface UnstakeGmxEventObject {
  account: string;
  token: string;
  amount: BigNumber;
}
export type UnstakeGmxEvent = TypedEvent<
  [string, string, BigNumber],
  UnstakeGmxEventObject
>;

export type UnstakeGmxEventFilter = TypedEventFilter<UnstakeGmxEvent>;

export interface RewardRouterV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RewardRouterV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptTransfer(
      _sender: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    batchCompoundForAccounts(
      _accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    batchStakeGmxForAccount(
      _accounts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    bnGmx(overrides?: CallOverrides): Promise<[string]>;

    bonusGmxTracker(overrides?: CallOverrides): Promise<[string]>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    claimEsGmx(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    claimFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    compound(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    compoundForAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    esGmx(overrides?: CallOverrides): Promise<[string]>;

    feeGlpTracker(overrides?: CallOverrides): Promise<[string]>;

    feeGmxTracker(overrides?: CallOverrides): Promise<[string]>;

    glp(overrides?: CallOverrides): Promise<[string]>;

    glpManager(overrides?: CallOverrides): Promise<[string]>;

    glpVester(overrides?: CallOverrides): Promise<[string]>;

    gmx(overrides?: CallOverrides): Promise<[string]>;

    gmxVester(overrides?: CallOverrides): Promise<[string]>;

    gov(overrides?: CallOverrides): Promise<[string]>;

    handleRewards(
      _shouldClaimGmx: PromiseOrValue<boolean>,
      _shouldStakeGmx: PromiseOrValue<boolean>,
      _shouldClaimEsGmx: PromiseOrValue<boolean>,
      _shouldStakeEsGmx: PromiseOrValue<boolean>,
      _shouldStakeMultiplierPoints: PromiseOrValue<boolean>,
      _shouldClaimWeth: PromiseOrValue<boolean>,
      _shouldConvertWethToEth: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    initialize(
      _weth: PromiseOrValue<string>,
      _gmx: PromiseOrValue<string>,
      _esGmx: PromiseOrValue<string>,
      _bnGmx: PromiseOrValue<string>,
      _glp: PromiseOrValue<string>,
      _stakedGmxTracker: PromiseOrValue<string>,
      _bonusGmxTracker: PromiseOrValue<string>,
      _feeGmxTracker: PromiseOrValue<string>,
      _feeGlpTracker: PromiseOrValue<string>,
      _stakedGlpTracker: PromiseOrValue<string>,
      _glpManager: PromiseOrValue<string>,
      _gmxVester: PromiseOrValue<string>,
      _glpVester: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    isInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    mintAndStakeGlp(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    mintAndStakeGlpETH(
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    pendingReceivers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    setGov(
      _gov: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    signalTransfer(
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stakeGmxForAccount(
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    stakedGlpTracker(overrides?: CallOverrides): Promise<[string]>;

    stakedGmxTracker(overrides?: CallOverrides): Promise<[string]>;

    unstakeAndRedeemGlp(
      _tokenOut: PromiseOrValue<string>,
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    unstakeAndRedeemGlpETH(
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    unstakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    unstakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;
  };

  acceptTransfer(
    _sender: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  batchCompoundForAccounts(
    _accounts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  batchStakeGmxForAccount(
    _accounts: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  bnGmx(overrides?: CallOverrides): Promise<string>;

  bonusGmxTracker(overrides?: CallOverrides): Promise<string>;

  claim(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  claimEsGmx(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  claimFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  compound(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  compoundForAccount(
    _account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  esGmx(overrides?: CallOverrides): Promise<string>;

  feeGlpTracker(overrides?: CallOverrides): Promise<string>;

  feeGmxTracker(overrides?: CallOverrides): Promise<string>;

  glp(overrides?: CallOverrides): Promise<string>;

  glpManager(overrides?: CallOverrides): Promise<string>;

  glpVester(overrides?: CallOverrides): Promise<string>;

  gmx(overrides?: CallOverrides): Promise<string>;

  gmxVester(overrides?: CallOverrides): Promise<string>;

  gov(overrides?: CallOverrides): Promise<string>;

  handleRewards(
    _shouldClaimGmx: PromiseOrValue<boolean>,
    _shouldStakeGmx: PromiseOrValue<boolean>,
    _shouldClaimEsGmx: PromiseOrValue<boolean>,
    _shouldStakeEsGmx: PromiseOrValue<boolean>,
    _shouldStakeMultiplierPoints: PromiseOrValue<boolean>,
    _shouldClaimWeth: PromiseOrValue<boolean>,
    _shouldConvertWethToEth: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  initialize(
    _weth: PromiseOrValue<string>,
    _gmx: PromiseOrValue<string>,
    _esGmx: PromiseOrValue<string>,
    _bnGmx: PromiseOrValue<string>,
    _glp: PromiseOrValue<string>,
    _stakedGmxTracker: PromiseOrValue<string>,
    _bonusGmxTracker: PromiseOrValue<string>,
    _feeGmxTracker: PromiseOrValue<string>,
    _feeGlpTracker: PromiseOrValue<string>,
    _stakedGlpTracker: PromiseOrValue<string>,
    _glpManager: PromiseOrValue<string>,
    _gmxVester: PromiseOrValue<string>,
    _glpVester: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  isInitialized(overrides?: CallOverrides): Promise<boolean>;

  mintAndStakeGlp(
    _token: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _minUsdg: PromiseOrValue<BigNumberish>,
    _minGlp: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  mintAndStakeGlpETH(
    _minUsdg: PromiseOrValue<BigNumberish>,
    _minGlp: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  pendingReceivers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<string>;

  setGov(
    _gov: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  signalTransfer(
    _receiver: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stakeEsGmx(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stakeGmx(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stakeGmxForAccount(
    _account: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  stakedGlpTracker(overrides?: CallOverrides): Promise<string>;

  stakedGmxTracker(overrides?: CallOverrides): Promise<string>;

  unstakeAndRedeemGlp(
    _tokenOut: PromiseOrValue<string>,
    _glpAmount: PromiseOrValue<BigNumberish>,
    _minOut: PromiseOrValue<BigNumberish>,
    _receiver: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  unstakeAndRedeemGlpETH(
    _glpAmount: PromiseOrValue<BigNumberish>,
    _minOut: PromiseOrValue<BigNumberish>,
    _receiver: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  unstakeEsGmx(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  unstakeGmx(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  withdrawToken(
    _token: PromiseOrValue<string>,
    _account: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptTransfer(
      _sender: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    batchCompoundForAccounts(
      _accounts: PromiseOrValue<string>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    batchStakeGmxForAccount(
      _accounts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    bnGmx(overrides?: CallOverrides): Promise<string>;

    bonusGmxTracker(overrides?: CallOverrides): Promise<string>;

    claim(overrides?: CallOverrides): Promise<void>;

    claimEsGmx(overrides?: CallOverrides): Promise<void>;

    claimFees(overrides?: CallOverrides): Promise<void>;

    compound(overrides?: CallOverrides): Promise<void>;

    compoundForAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    esGmx(overrides?: CallOverrides): Promise<string>;

    feeGlpTracker(overrides?: CallOverrides): Promise<string>;

    feeGmxTracker(overrides?: CallOverrides): Promise<string>;

    glp(overrides?: CallOverrides): Promise<string>;

    glpManager(overrides?: CallOverrides): Promise<string>;

    glpVester(overrides?: CallOverrides): Promise<string>;

    gmx(overrides?: CallOverrides): Promise<string>;

    gmxVester(overrides?: CallOverrides): Promise<string>;

    gov(overrides?: CallOverrides): Promise<string>;

    handleRewards(
      _shouldClaimGmx: PromiseOrValue<boolean>,
      _shouldStakeGmx: PromiseOrValue<boolean>,
      _shouldClaimEsGmx: PromiseOrValue<boolean>,
      _shouldStakeEsGmx: PromiseOrValue<boolean>,
      _shouldStakeMultiplierPoints: PromiseOrValue<boolean>,
      _shouldClaimWeth: PromiseOrValue<boolean>,
      _shouldConvertWethToEth: PromiseOrValue<boolean>,
      overrides?: CallOverrides,
    ): Promise<void>;

    initialize(
      _weth: PromiseOrValue<string>,
      _gmx: PromiseOrValue<string>,
      _esGmx: PromiseOrValue<string>,
      _bnGmx: PromiseOrValue<string>,
      _glp: PromiseOrValue<string>,
      _stakedGmxTracker: PromiseOrValue<string>,
      _bonusGmxTracker: PromiseOrValue<string>,
      _feeGmxTracker: PromiseOrValue<string>,
      _feeGlpTracker: PromiseOrValue<string>,
      _stakedGlpTracker: PromiseOrValue<string>,
      _glpManager: PromiseOrValue<string>,
      _gmxVester: PromiseOrValue<string>,
      _glpVester: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    isInitialized(overrides?: CallOverrides): Promise<boolean>;

    mintAndStakeGlp(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    mintAndStakeGlpETH(
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    pendingReceivers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<string>;

    setGov(
      _gov: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    signalTransfer(
      _receiver: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    stakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    stakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    stakeGmxForAccount(
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    stakedGlpTracker(overrides?: CallOverrides): Promise<string>;

    stakedGmxTracker(overrides?: CallOverrides): Promise<string>;

    unstakeAndRedeemGlp(
      _tokenOut: PromiseOrValue<string>,
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    unstakeAndRedeemGlpETH(
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    unstakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    unstakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {
    'StakeGlp(address,uint256)'(
      account?: null,
      amount?: null,
    ): StakeGlpEventFilter;
    StakeGlp(account?: null, amount?: null): StakeGlpEventFilter;

    'StakeGmx(address,address,uint256)'(
      account?: null,
      token?: null,
      amount?: null,
    ): StakeGmxEventFilter;
    StakeGmx(account?: null, token?: null, amount?: null): StakeGmxEventFilter;

    'UnstakeGlp(address,uint256)'(
      account?: null,
      amount?: null,
    ): UnstakeGlpEventFilter;
    UnstakeGlp(account?: null, amount?: null): UnstakeGlpEventFilter;

    'UnstakeGmx(address,address,uint256)'(
      account?: null,
      token?: null,
      amount?: null,
    ): UnstakeGmxEventFilter;
    UnstakeGmx(
      account?: null,
      token?: null,
      amount?: null,
    ): UnstakeGmxEventFilter;
  };

  estimateGas: {
    acceptTransfer(
      _sender: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    batchCompoundForAccounts(
      _accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    batchStakeGmxForAccount(
      _accounts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    bnGmx(overrides?: CallOverrides): Promise<BigNumber>;

    bonusGmxTracker(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    claimEsGmx(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    claimFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    compound(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    compoundForAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    esGmx(overrides?: CallOverrides): Promise<BigNumber>;

    feeGlpTracker(overrides?: CallOverrides): Promise<BigNumber>;

    feeGmxTracker(overrides?: CallOverrides): Promise<BigNumber>;

    glp(overrides?: CallOverrides): Promise<BigNumber>;

    glpManager(overrides?: CallOverrides): Promise<BigNumber>;

    glpVester(overrides?: CallOverrides): Promise<BigNumber>;

    gmx(overrides?: CallOverrides): Promise<BigNumber>;

    gmxVester(overrides?: CallOverrides): Promise<BigNumber>;

    gov(overrides?: CallOverrides): Promise<BigNumber>;

    handleRewards(
      _shouldClaimGmx: PromiseOrValue<boolean>,
      _shouldStakeGmx: PromiseOrValue<boolean>,
      _shouldClaimEsGmx: PromiseOrValue<boolean>,
      _shouldStakeEsGmx: PromiseOrValue<boolean>,
      _shouldStakeMultiplierPoints: PromiseOrValue<boolean>,
      _shouldClaimWeth: PromiseOrValue<boolean>,
      _shouldConvertWethToEth: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    initialize(
      _weth: PromiseOrValue<string>,
      _gmx: PromiseOrValue<string>,
      _esGmx: PromiseOrValue<string>,
      _bnGmx: PromiseOrValue<string>,
      _glp: PromiseOrValue<string>,
      _stakedGmxTracker: PromiseOrValue<string>,
      _bonusGmxTracker: PromiseOrValue<string>,
      _feeGmxTracker: PromiseOrValue<string>,
      _feeGlpTracker: PromiseOrValue<string>,
      _stakedGlpTracker: PromiseOrValue<string>,
      _glpManager: PromiseOrValue<string>,
      _gmxVester: PromiseOrValue<string>,
      _glpVester: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    isInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    mintAndStakeGlp(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    mintAndStakeGlpETH(
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    pendingReceivers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setGov(
      _gov: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    signalTransfer(
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stakeGmxForAccount(
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    stakedGlpTracker(overrides?: CallOverrides): Promise<BigNumber>;

    stakedGmxTracker(overrides?: CallOverrides): Promise<BigNumber>;

    unstakeAndRedeemGlp(
      _tokenOut: PromiseOrValue<string>,
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    unstakeAndRedeemGlpETH(
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    unstakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    unstakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptTransfer(
      _sender: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    batchCompoundForAccounts(
      _accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    batchStakeGmxForAccount(
      _accounts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    bnGmx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bonusGmxTracker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    claimEsGmx(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    claimFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    compound(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    compoundForAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    esGmx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeGlpTracker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeGmxTracker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    glp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    glpManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    glpVester(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gmx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gmxVester(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gov(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    handleRewards(
      _shouldClaimGmx: PromiseOrValue<boolean>,
      _shouldStakeGmx: PromiseOrValue<boolean>,
      _shouldClaimEsGmx: PromiseOrValue<boolean>,
      _shouldStakeEsGmx: PromiseOrValue<boolean>,
      _shouldStakeMultiplierPoints: PromiseOrValue<boolean>,
      _shouldClaimWeth: PromiseOrValue<boolean>,
      _shouldConvertWethToEth: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    initialize(
      _weth: PromiseOrValue<string>,
      _gmx: PromiseOrValue<string>,
      _esGmx: PromiseOrValue<string>,
      _bnGmx: PromiseOrValue<string>,
      _glp: PromiseOrValue<string>,
      _stakedGmxTracker: PromiseOrValue<string>,
      _bonusGmxTracker: PromiseOrValue<string>,
      _feeGmxTracker: PromiseOrValue<string>,
      _feeGlpTracker: PromiseOrValue<string>,
      _stakedGlpTracker: PromiseOrValue<string>,
      _glpManager: PromiseOrValue<string>,
      _gmxVester: PromiseOrValue<string>,
      _glpVester: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    isInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintAndStakeGlp(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    mintAndStakeGlpETH(
      _minUsdg: PromiseOrValue<BigNumberish>,
      _minGlp: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    pendingReceivers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    setGov(
      _gov: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    signalTransfer(
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stakeGmxForAccount(
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    stakedGlpTracker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stakedGmxTracker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unstakeAndRedeemGlp(
      _tokenOut: PromiseOrValue<string>,
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    unstakeAndRedeemGlpETH(
      _glpAmount: PromiseOrValue<BigNumberish>,
      _minOut: PromiseOrValue<BigNumberish>,
      _receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    unstakeEsGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    unstakeGmx(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;
  };
}
