/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as beefy from "./beefy";
export type { beefy };
import type * as gmx from "./gmx";
export type { gmx };
