/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AccessCardAccountCreator,
  AccessCardAccountCreatorInterface,
} from "../../access-card/AccessCardAccountCreator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_implementation",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "contract IERC721",
        name: "_nftContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_nftID",
        type: "uint256",
      },
    ],
    name: "deploy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_nftContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_nftID",
        type: "uint256",
      },
    ],
    name: "getAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AccessCardAccountCreator__factory {
  static readonly abi = _abi;
  static createInterface(): AccessCardAccountCreatorInterface {
    return new Interface(_abi) as AccessCardAccountCreatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccessCardAccountCreator {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AccessCardAccountCreator;
  }
}
