/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RewardRouterV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "batchCompoundForAccounts"
      | "batchStakeGmxForAccount"
      | "bnGmx"
      | "bonusGmxTracker"
      | "claim"
      | "claimEsGmx"
      | "claimFees"
      | "compound"
      | "compoundForAccount"
      | "esGmx"
      | "feeGlpTracker"
      | "feeGmxTracker"
      | "glp"
      | "glpManager"
      | "glpVester"
      | "gmx"
      | "gmxVester"
      | "gov"
      | "handleRewards"
      | "initialize"
      | "isInitialized"
      | "mintAndStakeGlp"
      | "mintAndStakeGlpETH"
      | "pendingReceivers"
      | "setGov"
      | "signalTransfer"
      | "stakeEsGmx"
      | "stakeGmx"
      | "stakeGmxForAccount"
      | "stakedGlpTracker"
      | "stakedGmxTracker"
      | "unstakeAndRedeemGlp"
      | "unstakeAndRedeemGlpETH"
      | "unstakeEsGmx"
      | "unstakeGmx"
      | "weth"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "StakeGlp"
      | "StakeGmx"
      | "UnstakeGlp"
      | "UnstakeGmx"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCompoundForAccounts",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchStakeGmxForAccount",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "bnGmx", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bonusGmxTracker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimEsGmx",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimFees", values?: undefined): string;
  encodeFunctionData(functionFragment: "compound", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "compoundForAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "esGmx", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeGlpTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeGmxTracker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "glp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "glpManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "glpVester", values?: undefined): string;
  encodeFunctionData(functionFragment: "gmx", values?: undefined): string;
  encodeFunctionData(functionFragment: "gmxVester", values?: undefined): string;
  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "handleRewards",
    values: [boolean, boolean, boolean, boolean, boolean, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAndStakeGlp",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAndStakeGlpETH",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingReceivers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setGov", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "signalTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeEsGmx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeGmx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeGmxForAccount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakedGlpTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakedGmxTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeAndRedeemGlp",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeAndRedeemGlpETH",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeEsGmx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeGmx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCompoundForAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchStakeGmxForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bnGmx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bonusGmxTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimEsGmx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "compound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "compoundForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "esGmx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeGlpTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeGmxTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "glp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "glpManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "glpVester", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gmx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gmxVester", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAndStakeGlp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAndStakeGlpETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingReceivers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signalTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeEsGmx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeGmx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeGmxForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakedGlpTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakedGmxTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeAndRedeemGlp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeAndRedeemGlpETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeEsGmx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstakeGmx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace StakeGlpEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeGmxEvent {
  export type InputTuple = [
    account: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [account: string, token: string, amount: bigint];
  export interface OutputObject {
    account: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakeGlpEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakeGmxEvent {
  export type InputTuple = [
    account: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [account: string, token: string, amount: bigint];
  export interface OutputObject {
    account: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardRouterV2 extends BaseContract {
  connect(runner?: ContractRunner | null): BaseContract;
  attach(addressOrName: AddressLike): this;
  deployed(): Promise<this>;

  interface: RewardRouterV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<
    [_sender: AddressLike],
    [void],
    "nonpayable"
  >;

  batchCompoundForAccounts: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  batchStakeGmxForAccount: TypedContractMethod<
    [_accounts: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  bnGmx: TypedContractMethod<[], [string], "view">;

  bonusGmxTracker: TypedContractMethod<[], [string], "view">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  claimEsGmx: TypedContractMethod<[], [void], "nonpayable">;

  claimFees: TypedContractMethod<[], [void], "nonpayable">;

  compound: TypedContractMethod<[], [void], "nonpayable">;

  compoundForAccount: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  esGmx: TypedContractMethod<[], [string], "view">;

  feeGlpTracker: TypedContractMethod<[], [string], "view">;

  feeGmxTracker: TypedContractMethod<[], [string], "view">;

  glp: TypedContractMethod<[], [string], "view">;

  glpManager: TypedContractMethod<[], [string], "view">;

  glpVester: TypedContractMethod<[], [string], "view">;

  gmx: TypedContractMethod<[], [string], "view">;

  gmxVester: TypedContractMethod<[], [string], "view">;

  gov: TypedContractMethod<[], [string], "view">;

  handleRewards: TypedContractMethod<
    [
      _shouldClaimGmx: boolean,
      _shouldStakeGmx: boolean,
      _shouldClaimEsGmx: boolean,
      _shouldStakeEsGmx: boolean,
      _shouldStakeMultiplierPoints: boolean,
      _shouldClaimWeth: boolean,
      _shouldConvertWethToEth: boolean
    ],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _weth: AddressLike,
      _gmx: AddressLike,
      _esGmx: AddressLike,
      _bnGmx: AddressLike,
      _glp: AddressLike,
      _stakedGmxTracker: AddressLike,
      _bonusGmxTracker: AddressLike,
      _feeGmxTracker: AddressLike,
      _feeGlpTracker: AddressLike,
      _stakedGlpTracker: AddressLike,
      _glpManager: AddressLike,
      _gmxVester: AddressLike,
      _glpVester: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  mintAndStakeGlp: TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _minUsdg: BigNumberish,
      _minGlp: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  mintAndStakeGlpETH: TypedContractMethod<
    [_minUsdg: BigNumberish, _minGlp: BigNumberish],
    [bigint],
    "payable"
  >;

  pendingReceivers: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  setGov: TypedContractMethod<[_gov: AddressLike], [void], "nonpayable">;

  signalTransfer: TypedContractMethod<
    [_receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeEsGmx: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeGmx: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  stakeGmxForAccount: TypedContractMethod<
    [_account: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakedGlpTracker: TypedContractMethod<[], [string], "view">;

  stakedGmxTracker: TypedContractMethod<[], [string], "view">;

  unstakeAndRedeemGlp: TypedContractMethod<
    [
      _tokenOut: AddressLike,
      _glpAmount: BigNumberish,
      _minOut: BigNumberish,
      _receiver: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  unstakeAndRedeemGlpETH: TypedContractMethod<
    [_glpAmount: BigNumberish, _minOut: BigNumberish, _receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;

  unstakeEsGmx: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstakeGmx: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  weth: TypedContractMethod<[], [string], "view">;

  withdrawToken: TypedContractMethod<
    [_token: AddressLike, _account: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[_sender: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchCompoundForAccounts"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchStakeGmxForAccount"
  ): TypedContractMethod<
    [_accounts: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bnGmx"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bonusGmxTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimEsGmx"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "compound"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "compoundForAccount"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "esGmx"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeGlpTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeGmxTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "glp"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "glpManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "glpVester"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gmx"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gmxVester"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gov"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleRewards"
  ): TypedContractMethod<
    [
      _shouldClaimGmx: boolean,
      _shouldStakeGmx: boolean,
      _shouldClaimEsGmx: boolean,
      _shouldStakeEsGmx: boolean,
      _shouldStakeMultiplierPoints: boolean,
      _shouldClaimWeth: boolean,
      _shouldConvertWethToEth: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _weth: AddressLike,
      _gmx: AddressLike,
      _esGmx: AddressLike,
      _bnGmx: AddressLike,
      _glp: AddressLike,
      _stakedGmxTracker: AddressLike,
      _bonusGmxTracker: AddressLike,
      _feeGmxTracker: AddressLike,
      _feeGlpTracker: AddressLike,
      _stakedGlpTracker: AddressLike,
      _glpManager: AddressLike,
      _gmxVester: AddressLike,
      _glpVester: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintAndStakeGlp"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _minUsdg: BigNumberish,
      _minGlp: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintAndStakeGlpETH"
  ): TypedContractMethod<
    [_minUsdg: BigNumberish, _minGlp: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "pendingReceivers"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setGov"
  ): TypedContractMethod<[_gov: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signalTransfer"
  ): TypedContractMethod<[_receiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeEsGmx"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeGmx"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeGmxForAccount"
  ): TypedContractMethod<
    [_account: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakedGlpTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakedGmxTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unstakeAndRedeemGlp"
  ): TypedContractMethod<
    [
      _tokenOut: AddressLike,
      _glpAmount: BigNumberish,
      _minOut: BigNumberish,
      _receiver: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstakeAndRedeemGlpETH"
  ): TypedContractMethod<
    [_glpAmount: BigNumberish, _minOut: BigNumberish, _receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstakeEsGmx"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeGmx"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [_token: AddressLike, _account: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "StakeGlp"
  ): TypedContractEvent<
    StakeGlpEvent.InputTuple,
    StakeGlpEvent.OutputTuple,
    StakeGlpEvent.OutputObject
  >;
  getEvent(
    key: "StakeGmx"
  ): TypedContractEvent<
    StakeGmxEvent.InputTuple,
    StakeGmxEvent.OutputTuple,
    StakeGmxEvent.OutputObject
  >;
  getEvent(
    key: "UnstakeGlp"
  ): TypedContractEvent<
    UnstakeGlpEvent.InputTuple,
    UnstakeGlpEvent.OutputTuple,
    UnstakeGlpEvent.OutputObject
  >;
  getEvent(
    key: "UnstakeGmx"
  ): TypedContractEvent<
    UnstakeGmxEvent.InputTuple,
    UnstakeGmxEvent.OutputTuple,
    UnstakeGmxEvent.OutputObject
  >;

  filters: {
    "StakeGlp(address,uint256)": TypedContractEvent<
      StakeGlpEvent.InputTuple,
      StakeGlpEvent.OutputTuple,
      StakeGlpEvent.OutputObject
    >;
    StakeGlp: TypedContractEvent<
      StakeGlpEvent.InputTuple,
      StakeGlpEvent.OutputTuple,
      StakeGlpEvent.OutputObject
    >;

    "StakeGmx(address,address,uint256)": TypedContractEvent<
      StakeGmxEvent.InputTuple,
      StakeGmxEvent.OutputTuple,
      StakeGmxEvent.OutputObject
    >;
    StakeGmx: TypedContractEvent<
      StakeGmxEvent.InputTuple,
      StakeGmxEvent.OutputTuple,
      StakeGmxEvent.OutputObject
    >;

    "UnstakeGlp(address,uint256)": TypedContractEvent<
      UnstakeGlpEvent.InputTuple,
      UnstakeGlpEvent.OutputTuple,
      UnstakeGlpEvent.OutputObject
    >;
    UnstakeGlp: TypedContractEvent<
      UnstakeGlpEvent.InputTuple,
      UnstakeGlpEvent.OutputTuple,
      UnstakeGlpEvent.OutputObject
    >;

    "UnstakeGmx(address,address,uint256)": TypedContractEvent<
      UnstakeGmxEvent.InputTuple,
      UnstakeGmxEvent.OutputTuple,
      UnstakeGmxEvent.OutputObject
    >;
    UnstakeGmx: TypedContractEvent<
      UnstakeGmxEvent.InputTuple,
      UnstakeGmxEvent.OutputTuple,
      UnstakeGmxEvent.OutputObject
    >;
  };
}
