name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 12,22 * * *'

jobs:
  unit-tests:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Yarn test up to 3 times
        shell: bash
        env:
          ZERO_X_PROXY_API_DOMAIN: ${{ secrets.ZERO_X_PROXY_API_DOMAIN }}
          ZERO_X_API_KEY: ${{ secrets.ZERO_X_API_KEY }}
        run: # Try yarn test 3 times before failing
          r=3;while ! yarn test ; do ((--r))||exit;sleep 1;done
